version: "3.8"
services:

  postgres:
    image: postgis/postgis:13-3.1
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  data: