version: "3.8"
services:

  postgres:
    build:
        context: .
        dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  data: