exports.seed = async function (knex) {
  const { id } = await knex('actores_politicos')
    .where('nombre_formatted', 'yumiko yerania palomarez herrera')
    .select('id')
    .first()

  await knex('diputacion_local').where('actor_politico_id', id).del()

  await knex.schema.raw(`
  insert into actores_politicos (nombre, puesto, img_url, created_at) values ('José Salvador Urzúa Solís ', 'Diputación Local Sonora por Distrito 1', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_256.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 1, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=256' from actores_politicos where nombre_formatted = lower(unaccent('José Salvador Urzúa Solís '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Hiram Lomelí Duarte ', 'Diputación Local Sonora por Distrito 2', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_257.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 2, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=257' from actores_politicos where nombre_formatted = lower(unaccent('Hiram Lomelí Duarte '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('María Alicia Gaytán Sánchez ', 'Diputación Local Sonora por Distrito 3', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_222.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 3, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=222' from actores_politicos where nombre_formatted = lower(unaccent('María Alicia Gaytán Sánchez '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Luis Armando Colosio Muñoz ', 'Diputación Local Sonora por Distrito 4', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_223.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 4, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=223' from actores_politicos where nombre_formatted = lower(unaccent('Luis Armando Colosio Muñoz '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('María Teresa Peralta Quijano ', 'Diputación Local Sonora por Distrito 5', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_258.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 5, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=258' from actores_politicos where nombre_formatted = lower(unaccent('María Teresa Peralta Quijano '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('María Teresa Valenzuela Muñoz ', 'Diputación Local Sonora por Distrito 6', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_255.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 6, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=255' from actores_politicos where nombre_formatted = lower(unaccent('María Teresa Valenzuela Muñoz '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Carlos Navarrete Aguirre ', 'Diputación Local Sonora por Distrito 7', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_226.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 7, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=226' from actores_politicos where nombre_formatted = lower(unaccent('Carlos Navarrete Aguirre '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Miroslava Luján López ', 'Diputación Local Sonora por Distrito 8', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_227.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 8, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=227' from actores_politicos where nombre_formatted = lower(unaccent('Miroslava Luján López '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Martín Matrecitos Flores ', 'Diputación Local Sonora por Distrito 9', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_228.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 9, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=228' from actores_politicos where nombre_formatted = lower(unaccent('Martín Matrecitos Flores '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Yumiko Yerania Palomarez Herrera ', 'Diputación Local Sonora por Distrito 10', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_229.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 10, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=229' from actores_politicos where nombre_formatted = lower(unaccent('Yumiko Yerania Palomarez Herrera '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Ma Magdalena Uribe Peña ', 'Diputación Local Sonora por Distrito 11', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_230.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 11, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=230' from actores_politicos where nombre_formatted = lower(unaccent('Ma Magdalena Uribe Peña '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Norberto Ortega Torres ', 'Diputación Local Sonora por Distrito 12', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_231.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 12, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=231' from actores_politicos where nombre_formatted = lower(unaccent('Norberto Ortega Torres '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Daniel Palafox Suárez ', 'Diputación Local Sonora por Distrito 13', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_253.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 13, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=253' from actores_politicos where nombre_formatted = lower(unaccent('Daniel Palafox Suárez '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Rosa María Mancha Ornelas ', 'Diputación Local Sonora por Distrito 14', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_233.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 14, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=233' from actores_politicos where nombre_formatted = lower(unaccent('Rosa María Mancha Ornelas '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Héctor Manuel Piñuelas León ', 'Diputación Local Sonora por Distrito 15', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_254.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 15, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=254' from actores_politicos where nombre_formatted = lower(unaccent('Héctor Manuel Piñuelas León '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Juan Gabriel Pérez Pérez ', 'Diputación Local Sonora por Distrito 16', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_259.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 16, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=259' from actores_politicos where nombre_formatted = lower(unaccent('Juan Gabriel Pérez Pérez '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Ernestina Castro Valenzuela ', 'Diputación Local Sonora por Distrito 17', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_236.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 17, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=236' from actores_politicos where nombre_formatted = lower(unaccent('Ernestina Castro Valenzuela '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Fermín Trujillo Fuentes ', 'Diputación Local Sonora por Distrito 18', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_237.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 18, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=237' from actores_politicos where nombre_formatted = lower(unaccent('Fermín Trujillo Fuentes '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Patricia Pacheco Borbón ', 'Diputación Local Sonora por Distrito 19', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_260.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 19, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=260' from actores_politicos where nombre_formatted = lower(unaccent('Patricia Pacheco Borbón '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Marcia Lorena Camarena Moncada ', 'Diputación Local Sonora por Distrito 20', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_239.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 20, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=239' from actores_politicos where nombre_formatted = lower(unaccent('Marcia Lorena Camarena Moncada '));
insert into actores_politicos (nombre, puesto, img_url, created_at) values ('Filemón Ortega Quintos ', 'Diputación Local Sonora por Distrito 21', 'http://www.congresoson.gob.mx/Images/fotos_dip/dip_240.jpg', '2021-05-02 13:00:00') ON CONFLICT DO NOTHING;
insert into diputacion_local(actor_politico_id, periodo, distrito_local, estado, link) select id, '[2018-12-01,2021-12-02)'::daterange, 21, 26, 'http://www.congresoson.gob.mx/Legislatura/DiputadoPreview\\?id=240' from actores_politicos where nombre_formatted = lower(unaccent('Filemón Ortega Quintos '));
  `)
}
